name: Unzip Static Content

on:
  push:
    branches:
      - main

jobs:
  unzip_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create static folder (if it doesn't exist)
        run: mkdir -p static

      - name: CD to static folder (if it doesn't exist)
        run: cd  static

      - name: Unzip content to static folder
        run: unzip -o UpstoxWSS_07_10_25.zip -d .
